version: "0.2"
words:
  - armhf
  - armv
  - asyncio
  - autoclass
  - automethod
  - automodule
  - binstall
  - binutils
  - bndy
  - cdylib
  - clippy
  - cooldown
  - currentmodule
  - Doherty
  - endfor
  - endmacro
  - esac
  - fontlist
  - fontsource
  - furo
  - gnueabi
  - gnueabihf
  - hustcer
  - libc
  - manylinux
  - maturin
  - msvc
  - musllinux
  - mypy
  - nextest
  - nurfile
  - pathlib
  - pipx
  - prek
  - pyclass
  - pyfunction
  - pymethods
  - pymodule
  - pypa
  - pypi
  - pyproject
  - pytest
  - reqwest
  - roboto
  - rustup
  - sccache
  - sdist
  - serde
  - staticmethod
  - thiserror
  - venv
  - zizmor
ignorePaths:
  - .venv/
  - .gitignore
  - .gitattributes
  - tests/*.json
  - CHANGELOG.md
