from pathlib import Path
from typing import NamedTuple
from enum import IntEnum

class FontSourceClient:
    def __init__(self, cache_root: Path | None = None) -> None: ...
    async def download_font(self, font: FontQuery) -> Path: ...
    def families_cache_path(self) -> Path: ...
    def font_list_cache_path(self) -> Path: ...

class Weight(IntEnum):
    Thin = (100,)
    ExtraLight = (200,)
    Light = (300,)
    Normal = (400,)
    Medium = (500,)
    SemiBold = (600,)
    Bold = (700,)
    ExtraBold = (800,)
    Black = (900,)

    def __init__(self, value: int) -> None: ...
    def __int__(self) -> int: ...

class FontQuery(NamedTuple):
    family: str = ...
    style: str | None = ...
    weight: Weight | None = ...
    subset: str | None = ...
